<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/02/15 12:39:14

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=walnut',
  'username' => 'root',
  'password' => 'StU8e@uh',
  'name' => 'doctrine',
)),);
