<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/03/28 02:36:43

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=walnut',
  'username' => 'root',
  'password' => 'StU8e@uh',
  'name' => 'doctrine',
)),);
