<?php
// auto-generated by sfViewConfigHandler
// date: 2012/04/05 02:50:15
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);
  $response->addMeta('title', '核桃', false, false);
  $response->addMeta('description', '核桃, 视觉', false, false);
  $response->addMeta('keywords', 'mobile, iphone, android, location, 时尚, 核桃, 视觉, 电子商务, 搜索', false, false);
  $response->addMeta('language', 'utf-8', false, false);
  $response->addMeta('robots', 'index, follow', false, false);

  $response->addStylesheet('bootstrap.css', '', array ());
  $response->addStylesheet('bootstrap-responsive.css', '', array ());
  $response->addStylesheet('walnut.css', '', array ());
  $response->addJavascript('jquery-1.7.2.min.js', '', array ());
  $response->addJavascript('bootstrap.js', '', array ());
  $response->addJavascript('bootstrap-tab.js', '', array ());
  $response->addJavascript('bootstrap-carousel.js', '', array ());
  $response->addJavascript('walnut.js', '', array ());


