# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        核桃
    description:  核桃, 视觉
    keywords:     mobile, iphone, android, location, 时尚, 核桃, 视觉, 电子商务, 搜索
    language:     utf-8
    robots:       index, follow

  stylesheets:    [bootstrap.css, bootstrap-responsive.css, walnut.css]

  javascripts:    [jquery-1.7.2.min.js, bootstrap.js, bootstrap-tab.js, bootstrap-carousel.js, walnut.js]

  has_layout:     true
  layout:         layout